version: "3.4"
services:
  camunda-engine:
    image: camunda/camunda-bpm-platform:7.14.0
    hostname: camunda-engine
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://camunda-db:5432/camunda-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    ports:
      - "8080:8080"
    networks:
      - camunda-network
    depends_on:
      - camunda-db
  camunda-db:
    image: postgres:12.1
    hostname: camunda-db
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DB=camunda-engine
    volumes:
      - db-storage:/var/lib/postgresql/data
    networks:
      - camunda-network

volumes:
  db-storage:
    driver: local

networks:
  camunda-network: